### ISSUE TITLE
Remove POGS?

### ISSUE THREAD

**Issue by troyengel** [nexus-prime/QuickMag#3]
Now that POGS is complete, we should remove it?

```
$ bash UpdateDatabaseFiles.sh cpu
Skipping gpu projects
Starting 16 downloads...
 
Progress: 6%
gzip: ./TeamFiles/POGSteam.gz: not in gzip format
Progress: 6%
gzip: POGShosts.gz: not in gzip format
Progress: 69%
```

**Comment by nexus-prime** [comment]
I was planning on removing it over the weekend, but got sidetracked. Thanks for reminding me. I'll also comment out the WCG sections until this GDPR stuff gets sorted out.

**Comment by nexus-prime** [comment]
The necessary changes have been made. POGS has been removed and WCG commented out until the GDPR issues get fixed.
