### ISSUE TITLE
GPU Names are randomly different for same card

### ISSUE THREAD

**Issue by vseven** [nexus-prime/QuickMag#5]
For example the following three all give different results:

bash GPU_QuickMag.sh "TITAN V" 20
bash GPU_QuickMag.sh "TITAN V|1|" 20
bash GPU_QuickMag.sh "TITAN V|2|" 20

I would assume the 2 means that user is running 2 Titan V's but I know that not always correct.  I say that because I have a Titan V and a 1080 but in BOINC stats it lists as:

2x CUDA
TITAN V (2x)
OpenCL 1.2 CUDA 9.2.127/398.11

I'm guessing it sees the Titan first then just says there both cuda so they must be the same even though they are not (very much not).  But shouldn't TITAN V and TITAN V|1| be the same?

Currently I'm getting around that by using "TITAN V*" which seems to work.  

More of a FYI then a issue but it should be noted somewhere.

**Comment by nexus-prime** [comment]
I've thought about removing the |1| from the gpu names and then adding it in the code. The only issue is the dual GPUs. However the dual GPU cards are fairly rare and we usually don't have good statistics for them... 
I guess I'll think about ways to mitigate the issue so I can make the change.

**Comment by vseven** [comment]
Closing.
